/**
 * CEAC's NIV (nonimmigrant/DS-160) "Location" dropdown — the consulate the
 * application was filed at. Copied directly from the live
 * `#Location_Dropdown` on https://ceac.state.gov/CEACStatTracker/Status.aspx
 * (inspected 2026-09-16) rather than guessed, so the codes match exactly
 * what CEAC's own `<option value="...">` expects.
 *
 * Bundled here rather than read from the page at runtime: instant to show
 * in the add-case picker (no waiting on a page load first), and this list
 * changes rarely. Tradeoff, accepted: if the State Department adds or
 * renames a post, this goes stale until updated by hand — low-risk and
 * easy to fix (a location that's gone is simply missing from the picker,
 * not silently wrong).
 *
 * Labels are copied verbatim, including CEAC's own typos (N`DJAMENA,
 * COTE D`IVORIE use a backtick, not an apostrophe) — this should read
 * exactly like the option a user would see on CEAC's own site.
 */
export interface CeacLocation {
  code: string;
  label: string;
}

export const CEAC_LOCATIONS: CeacLocation[] = [
  { code: "KBL", label: "AFGHANISTAN, KABUL" },
  { code: "TIA", label: "ALBANIA, TIRANA" },
  { code: "ALG", label: "ALGERIA, ALGIERS" },
  { code: "LUA", label: "ANGOLA, LUANDA" },
  { code: "BNS", label: "ARGENTINA, BUENOS AIRES" },
  { code: "YRV", label: "ARMENIA, YEREVAN" },
  { code: "MLB", label: "AUSTRALIA, MELBOURNE" },
  { code: "PRT", label: "AUSTRALIA, PERTH" },
  { code: "SYD", label: "AUSTRALIA, SYDNEY" },
  { code: "VNN", label: "AUSTRIA, VIENNA" },
  { code: "BKU", label: "AZERBAIJAN, BAKU" },
  { code: "NSS", label: "BAHAMAS, NASSAU" },
  { code: "MNA", label: "BAHRAIN, MANAMA" },
  { code: "DHK", label: "BANGLADESH, DHAKA" },
  { code: "BGN", label: "BARBADOS, BRIDGETOWN" },
  { code: "MSK", label: "BELARUS, MINSK" },
  { code: "BRS", label: "BELGIUM, BRUSSELS" },
  { code: "BLZ", label: "BELIZE, BELMOPAN" },
  { code: "COT", label: "BENIN, COTONOU" },
  { code: "HML", label: "BERMUDA, HAMILTON" },
  { code: "LPZ", label: "BOLIVIA, LA PAZ" },
  { code: "SAR", label: "BOSNIA-HERZEGOVINA, SARAJEVO" },
  { code: "GAB", label: "BOTSWANA, GABORONE" },
  { code: "BRA", label: "BRAZIL, BRASILIA" },
  { code: "PTA", label: "BRAZIL, PORTO ALEGRE" },
  { code: "RCF", label: "BRAZIL, RECIFE" },
  { code: "RDJ", label: "BRAZIL, RIO DE JANEIRO" },
  { code: "SPL", label: "BRAZIL, SAO PAULO" },
  { code: "BSB", label: "BRUNEI, BANDAR SERI BEGAWAN" },
  { code: "SOF", label: "BULGARIA, SOFIA" },
  { code: "OUG", label: "BURKINA FASO, OUAGADOUGOU" },
  { code: "RNG", label: "BURMA, RANGOON" },
  { code: "BUJ", label: "BURUNDI, BUJUMBURA" },
  { code: "PIA", label: "CABO VERDE, PRAIA" },
  { code: "PHP", label: "CAMBODIA, PHNOM PENH" },
  { code: "YDE", label: "CAMEROON, YAOUNDE" },
  { code: "CLG", label: "CANADA, CALGARY" },
  { code: "HLF", label: "CANADA, HALIFAX" },
  { code: "MTL", label: "CANADA, MONTREAL" },
  { code: "OTT", label: "CANADA, OTTAWA" },
  { code: "QBC", label: "CANADA, QUEBEC" },
  { code: "TRT", label: "CANADA, TORONTO" },
  { code: "VAC", label: "CANADA, VANCOUVER" },
  { code: "NDJ", label: "CHAD, N`DJAMENA" },
  { code: "SNT", label: "CHILE, SANTIAGO" },
  { code: "BEJ", label: "CHINA, BEIJING" },
  { code: "CHE", label: "CHINA, CHENGDU" },
  { code: "GUZ", label: "CHINA, GUANGZHOU" },
  { code: "SHG", label: "CHINA, SHANGHAI" },
  { code: "SNY", label: "CHINA, SHENYANG" },
  { code: "WUH", label: "CHINA, WUHAN" },
  { code: "BGT", label: "COLOMBIA, BOGOTA" },
  { code: "BRZ", label: "CONGO, BRAZZAVILLE" },
  { code: "KIN", label: "CONGO, KINSHASA" },
  { code: "SNJ", label: "COSTA RICA, SAN JOSE" },
  { code: "ABJ", label: "COTE D`IVORIE, ABIDJAN" },
  { code: "ZGB", label: "CROATIA, ZAGREB" },
  { code: "HAV", label: "CUBA, HAVANA" },
  { code: "CRC", label: "CURACAO, CURACAO" },
  { code: "NCS", label: "CYPRUS, NICOSIA" },
  { code: "PRG", label: "CZECH REPUBLIC, PRAGUE" },
  { code: "CPN", label: "DENMARK, COPENHAGEN" },
  { code: "DJI", label: "DJIBOUTI, DJIBOUTI" },
  { code: "SDO", label: "DOMINICAN REPUBLIC, SANTO DOMINGO" },
  { code: "GYQ", label: "ECUADOR, GUAYAQUIL" },
  { code: "QTO", label: "ECUADOR, QUITO" },
  { code: "CRO", label: "EGYPT, CAIRO" },
  { code: "SNS", label: "EL SALVADOR, SAN SALVADOR" },
  { code: "LND", label: "ENGLAND, LONDON" },
  { code: "MBO", label: "EQUATORIAL GUINEA, MALABO" },
  { code: "ASM", label: "ERITREA, ASMARA" },
  { code: "TAL", label: "ESTONIA, TALLINN" },
  { code: "MBA", label: "ESWATINI, MBABANE" },
  { code: "ADD", label: "ETHIOPIA, ADDIS ABABA" },
  { code: "SUV", label: "FIJI, SUVA" },
  { code: "HLS", label: "FINLAND, HELSINKI" },
  { code: "PRS", label: "FRANCE, PARIS" },
  { code: "LIB", label: "GABON, LIBREVILLE" },
  { code: "BAN", label: "GAMBIA, BANJUL" },
  { code: "TBL", label: "GEORGIA, TBILISI" },
  { code: "BRL", label: "GERMANY, BERLIN" },
  { code: "FRN", label: "GERMANY, FRANKFURT" },
  { code: "MUN", label: "GERMANY, MUNICH" },
  { code: "ACC", label: "GHANA, ACCRA" },
  { code: "ATH", label: "GREECE, ATHENS" },
  { code: "GTM", label: "GUATEMALA, GUATEMALA CITY" },
  { code: "CRY", label: "GUINEA, CONAKRY" },
  { code: "GEO", label: "GUYANA, GEORGETOWN" },
  { code: "PTP", label: "HAITI, PORT-AU-PRINCE" },
  { code: "TGG", label: "HONDURAS, TEGUCIGALPA" },
  { code: "HNK", label: "HONG KONG" },
  { code: "BDP", label: "HUNGARY, BUDAPEST" },
  { code: "RKJ", label: "ICELAND, REYKJAVIK" },
  { code: "MDR", label: "INDIA, CHENNAI" },
  { code: "HYD", label: "INDIA, HYDERABAD" },
  { code: "CLC", label: "INDIA, KOLKATA" },
  { code: "BMB", label: "INDIA, MUMBAI" },
  { code: "NWD", label: "INDIA, NEW DELHI" },
  { code: "JAK", label: "INDONESIA, JAKARTA" },
  { code: "SRB", label: "INDONESIA, SURABAYA" },
  { code: "BGH", label: "IRAQ, BAGHDAD" },
  { code: "ERB", label: "IRAQ, ERBIL" },
  { code: "DBL", label: "IRELAND, DUBLIN" },
  { code: "TLV", label: "ISRAEL, TEL AVIV" },
  { code: "FLR", label: "ITALY, FLORENCE" },
  { code: "MLN", label: "ITALY, MILAN" },
  { code: "NPL", label: "ITALY, NAPLES" },
  { code: "RME", label: "ITALY, ROME" },
  { code: "KNG", label: "JAMAICA, KINGSTON" },
  { code: "FKK", label: "JAPAN, FUKUOKA" },
  { code: "NHA", label: "JAPAN, NAHA" },
  { code: "KBO", label: "JAPAN, OSAKA" },
  { code: "SPP", label: "JAPAN, SAPPORO" },
  { code: "TKY", label: "JAPAN, TOKYO" },
  { code: "JRS", label: "JERUSALEM" },
  { code: "AMM", label: "JORDAN, AMMAN" },
  { code: "ATA", label: "KAZAKHSTAN, ALMATY" },
  { code: "AST", label: "KAZAKHSTAN, ASTANA" },
  { code: "NRB", label: "KENYA, NAIROBI" },
  { code: "PRI", label: "KOSOVO, PRISTINA" },
  { code: "KWT", label: "KUWAIT, KUWAIT CITY" },
  { code: "BKK", label: "KYRGYZSTAN, BISHKEK" },
  { code: "VNT", label: "LAOS, VIENTIANE" },
  { code: "RGA", label: "LATVIA, RIGA" },
  { code: "BRT", label: "LEBANON, BEIRUT" },
  { code: "MAS", label: "LESOTHO, MASERU" },
  { code: "MRV", label: "LIBERIA, MONROVIA" },
  { code: "VIL", label: "LITHUANIA, VILNIUS" },
  { code: "LXM", label: "LUXEMBOURG, LUXEMBOURG" },
  { code: "ANT", label: "MADAGASCAR, ANTANANARIVO" },
  { code: "LIL", label: "MALAWI, LILONGWE" },
  { code: "KLL", label: "MALAYSIA, KUALA LUMPUR" },
  { code: "BAM", label: "MALI, BAMAKO" },
  { code: "VLL", label: "MALTA, VALLETTA" },
  { code: "MAJ", label: "MARSHALL ISLANDS, MAJURO" },
  { code: "NUK", label: "MAURITANIA, NOUAKCHOTT" },
  { code: "PTL", label: "MAURITIUS, PORT LOUIS" },
  { code: "CDJ", label: "MEXICO, CIUDAD JUAREZ" },
  { code: "GDL", label: "MEXICO, GUADALAJARA" },
  { code: "HER", label: "MEXICO, HERMOSILLO" },
  { code: "MTM", label: "MEXICO, MATAMOROS" },
  { code: "MER", label: "MEXICO, MERIDA" },
  { code: "MEX", label: "MEXICO, MEXICO CITY" },
  { code: "MTR", label: "MEXICO, MONTERREY" },
  { code: "NGL", label: "MEXICO, NOGALES" },
  { code: "NVL", label: "MEXICO, NUEVO LAREDO" },
  { code: "TJT", label: "MEXICO, TIJUANA" },
  { code: "KOL", label: "MICRONESIA, KOLONIA" },
  { code: "CHS", label: "MOLDOVA, CHISINAU" },
  { code: "ULN", label: "MONGOLIA, ULAANBAATAR" },
  { code: "POD", label: "MONTENEGRO, PODGORICA" },
  { code: "CSB", label: "MOROCCO, CASABLANCA" },
  { code: "MAP", label: "MOZAMBIQUE, MAPUTO" },
  { code: "WHK", label: "NAMIBIA, WINDHOEK" },
  { code: "KDU", label: "NEPAL, KATHMANDU" },
  { code: "AMS", label: "NETHERLANDS, AMSTERDAM" },
  { code: "USN", label: "NEW YORK, NY - USA" },
  { code: "ACK", label: "NEW ZEALAND, AUCKLAND" },
  { code: "MNG", label: "NICARAGUA, MANAGUA" },
  { code: "NMY", label: "NIGER, NIAMEY" },
  { code: "ABU", label: "NIGERIA, ABUJA" },
  { code: "LGS", label: "NIGERIA, LAGOS" },
  { code: "SKO", label: "NORTH MACEDONIA, SKOPJE" },
  { code: "BLF", label: "NORTHERN IRELAND, BELFAST" },
  { code: "OSL", label: "NORWAY, OSLO" },
  { code: "MST", label: "OMAN, MUSCAT" },
  { code: "ISL", label: "PAKISTAN, ISLAMABAD" },
  { code: "KRC", label: "PAKISTAN, KARACHI" },
  { code: "LHR", label: "PAKISTAN, LAHORE" },
  { code: "KOR", label: "PALAU, KOROR" },
  { code: "PNM", label: "PANAMA, PANAMA CITY" },
  { code: "PTM", label: "PAPUA NEW GUINEA, PORT MORESBY" },
  { code: "ASN", label: "PARAGUAY, ASUNCION" },
  { code: "LMA", label: "PERU, LIMA" },
  { code: "MNL", label: "PHILIPPINES, MANILA" },
  { code: "KRK", label: "POLAND, KRAKOW" },
  { code: "WRW", label: "POLAND, WARSAW" },
  { code: "LSB", label: "PORTUGAL, LISBON" },
  { code: "DOH", label: "QATAR, DOHA" },
  { code: "BCH", label: "ROMANIA, BUCHAREST" },
  { code: "MOS", label: "RUSSIA, MOSCOW" },
  { code: "VLA", label: "RUSSIA, VLADIVOSTOK" },
  { code: "YEK", label: "RUSSIA, YEKATERINBURG" },
  { code: "KGL", label: "RWANDA, KILGALI" },
  { code: "APA", label: "SAMOA, APIA" },
  { code: "DHR", label: "SAUDI ARABIA, DHAHRAN" },
  { code: "JDD", label: "SAUDI ARABIA, JEDDAH" },
  { code: "RID", label: "SAUDI ARABIA, RIYADH" },
  { code: "DKR", label: "SENEGAL, DAKAR" },
  { code: "BLG", label: "SERBIA, BELGRADE" },
  { code: "FTN", label: "SIERRA LEONE, FREETOWN" },
  { code: "SGP", label: "SINGAPORE, SINGAPORE" },
  { code: "BTS", label: "SLOVAKIA, BRATISLAVA" },
  { code: "LJU", label: "SLOVENIA, LJUBLJANA" },
  { code: "CPT", label: "SOUTH AFRICA, CAPE TOWN" },
  { code: "DRB", label: "SOUTH AFRICA, DURBAN" },
  { code: "JHN", label: "SOUTH AFRICA, JOHANNESBURG" },
  { code: "SEO", label: "SOUTH KOREA, SEOUL" },
  { code: "JBA", label: "SOUTH SUDAN, JUBA" },
  { code: "MDD", label: "SPAIN, MADRID" },
  { code: "CLM", label: "SRI LANKA, COLOMBO" },
  { code: "KHT", label: "SUDAN, KHARTOUM" },
  { code: "PRM", label: "SURINAME, PARAMARIBO" },
  { code: "STK", label: "SWEDEN, STOCKHOLM" },
  { code: "BEN", label: "SWITZERLAND, BERN" },
  { code: "TAI", label: "TAIWAN, TAIPEI" },
  { code: "DHB", label: "TAJIKISTAN, DUSHANBE" },
  { code: "DRS", label: "TANZANIA, DAR ES SALAAM" },
  { code: "BNK", label: "THAILAND, BANGKOK" },
  { code: "CHN", label: "THAILAND, CHIANG MAI" },
  { code: "DIL", label: "TIMOR LESTE, DILI" },
  { code: "LOM", label: "TOGO, LOME" },
  { code: "PTS", label: "TRINIDAD, PORT OF SPAIN" },
  { code: "TNS", label: "TUNISIA, TUNIS" },
  { code: "ANK", label: "TURKEY, ANKARA" },
  { code: "IST", label: "TURKEY, ISTANBUL" },
  { code: "AKD", label: "TURKMENISTAN, ASHGABAT" },
  { code: "USA", label: "U.S. - DOMESTIC" },
  { code: "KMP", label: "UGANDA, KAMPALA" },
  { code: "KEV", label: "UKRAINE, KYIV" },
  { code: "ABD", label: "UNITED ARAB EMIRATES, ABU DHABI" },
  { code: "DUB", label: "UNITED ARAB EMIRATES, DUBAI" },
  { code: "MTV", label: "URUGUAY, MONTEVIDEO" },
  { code: "THT", label: "UZBEKISTAN, TASHKENT" },
  { code: "HAN", label: "VIETNAM, HANOI" },
  { code: "HCM", label: "VIETNAM, HO CHI MINH CITY" },
  { code: "DPT", label: "WASHINGTON, DC - USA" },
  { code: "LUS", label: "ZAMBIA, LUSAKA" },
  { code: "HRE", label: "ZIMBABWE, HARARE" },
];
