/**
 * EOIR's own nationality list, fetched verbatim on 2026-09-17 from the
 * Gatsby static query that ACIS's nationality dropdown itself is built
 * from (acis.eoir.justice.gov/page-data/sq/d/1791802679.json), filtered
 * the same way their own code filters it (they drop code "??",
 * "UNKNOWN NATIONALITY").
 *
 * The codes are EOIR's OWN, NOT ISO 3166 — ARUBA is "AB", ALGERIA "AG",
 * AUSTRALIA "AS", CHINA "CH". Guessing them from ISO would be wrong for a
 * large fraction of the list, which is exactly why this is transcribed
 * from their data rather than generated.
 *
 * ACIS renders each option as `NAME + " (" + CODE + ")"`, so
 * eoirNationalityLabel() below reproduces their label exactly and autofill
 * can match an option by full string equality. That matters: an earlier
 * version matched on "does the option text contain the country name",
 * which picked BRITISH INDIAN OCEAN TERRITORY for INDIA (it contains
 * "INDIA", and sorts first alphabetically).
 */
export interface EoirNationality {
  /** EOIR's own 2-letter code, the value their API's natCode expects. */
  code: string;
  name: string;
}

export const EOIR_NATIONALITIES: EoirNationality[] = [
  { code: "AF", name: "AFGHANISTAN" },
  { code: "AL", name: "ALBANIA" },
  { code: "AG", name: "ALGERIA" },
  { code: "AN", name: "ANDORRA" },
  { code: "AO", name: "ANGOLA" },
  { code: "AV", name: "ANGUILLA" },
  { code: "AC", name: "ANTIGUA AND BARBUDA" },
  { code: "AR", name: "ARGENTINA" },
  { code: "AM", name: "ARMENIA" },
  { code: "AB", name: "ARUBA" },
  { code: "AS", name: "AUSTRALIA" },
  { code: "AU", name: "AUSTRIA" },
  { code: "AZ", name: "AZERBAIJAN" },
  { code: "BF", name: "BAHAMAS" },
  { code: "BA", name: "BAHRAIN" },
  { code: "BG", name: "BANGLADESH" },
  { code: "BB", name: "BARBADOS" },
  { code: "XX", name: "BE REMOVED FROM THE UNITED STATES" },
  { code: "BZ", name: "BELARUS" },
  { code: "BE", name: "BELGIUM" },
  { code: "BH", name: "BELIZE" },
  { code: "BN", name: "BENIN" },
  { code: "BD", name: "BERMUDA" },
  { code: "BT", name: "BHUTAN" },
  { code: "BL", name: "BOLIVIA" },
  { code: "BI", name: "BOSNIA-HERZEGOVINA" },
  { code: "BC", name: "BOTSWANA" },
  { code: "BV", name: "BOUVET ISLAND" },
  { code: "BR", name: "BRAZIL" },
  { code: "IO", name: "BRITISH INDIAN OCEAN TERRITORY" },
  { code: "VI", name: "BRITISH VIRGIN ISLANDS" },
  { code: "BW", name: "BRITISH WEST INDIES" },
  { code: "BX", name: "BRUNEI" },
  { code: "BU", name: "BULGARIA" },
  { code: "BO", name: "BURKINA FASO" },
  { code: "BM", name: "BURMA (MYANMAR)" },
  { code: "BY", name: "BURUNDI" },
  { code: "BS", name: "BYELORUSSIA (BELARUS)" },
  { code: "CC", name: "CAMBODIA" },
  { code: "CM", name: "CAMEROON" },
  { code: "CA", name: "CANADA" },
  { code: "CV", name: "CAPE VERDE" },
  { code: "CJ", name: "CAYMAN ISLANDS" },
  { code: "CT", name: "CENTRAL AFRICAN REPUBLIC" },
  { code: "CD", name: "CHAD" },
  { code: "CI", name: "CHILE" },
  { code: "CH", name: "CHINA" },
  { code: "KT", name: "CHRISTMAS ISLANDS" },
  { code: "CK", name: "COCOS ISLAND" },
  { code: "CO", name: "COLOMBIA" },
  { code: "CN", name: "COMORO ISLANDS" },
  { code: "CF", name: "CONGO" },
  { code: "CW", name: "COOK ISLANDS" },
  { code: "CS", name: "COSTA RICA" },
  { code: "CX", name: "CROATIA" },
  { code: "CU", name: "CUBA" },
  { code: "CY", name: "CYPRUS" },
  { code: "CR", name: "CZECH REPUBLIC" },
  { code: "DC", name: "DEMOCRATIC REPUBLIC OF CONGO" },
  { code: "DA", name: "DENMARK" },
  { code: "DJ", name: "DJIBOUTI" },
  { code: "DO", name: "DOMINICA" },
  { code: "DR", name: "DOMINICAN REPUBLIC" },
  { code: "TM", name: "EAST TIMOR" },
  { code: "EC", name: "ECUADOR" },
  { code: "EG", name: "EGYPT" },
  { code: "ES", name: "EL SALVADOR" },
  { code: "EK", name: "EQUATORIAL GUINEA" },
  { code: "ER", name: "ERITREA" },
  { code: "EO", name: "ESTONIA" },
  { code: "ET", name: "ETHIOPIA" },
  { code: "FO", name: "FAEROE ISLAND" },
  { code: "FA", name: "FALKLAND ISLANDS" },
  { code: "FM", name: "FEDERATED STATES OF MICRONESIA" },
  { code: "FJ", name: "FIJI" },
  { code: "FI", name: "FINLAND" },
  { code: "FR", name: "FRANCE" },
  { code: "FG", name: "FRENCH GUIANA" },
  { code: "FP", name: "FRENCH POLYNESIA" },
  { code: "FS", name: "FRENCH SOUTHERN AND ANTARCTIC LANDS" },
  { code: "FW", name: "FRENCH WEST INDIES" },
  { code: "CZ", name: "Former Countries" },
  { code: "GC", name: "Former Countries" },
  { code: "UR", name: "Former Countries" },
  { code: "YO", name: "Former Countries" },
  { code: "YS", name: "Former Countries" },
  { code: "GB", name: "GABON" },
  { code: "GA", name: "GAMBIA" },
  { code: "GZ", name: "GAZA STRIP" },
  { code: "GO", name: "GEORGIA" },
  { code: "GE", name: "GERMANY" },
  { code: "GH", name: "GHANA" },
  { code: "GI", name: "GIBRALTAR" },
  { code: "GR", name: "GREECE" },
  { code: "GL", name: "GREENLAND" },
  { code: "GJ", name: "GRENADA" },
  { code: "GP", name: "GUADELOUPE" },
  { code: "GT", name: "GUATEMALA" },
  { code: "GV", name: "GUINEA" },
  { code: "PU", name: "GUINEA BISSAU" },
  { code: "GY", name: "GUYANA" },
  { code: "HA", name: "HAITI" },
  { code: "HM", name: "HEARD AND MCDONALD ISLANDS" },
  { code: "HL", name: "HOLLAND" },
  { code: "HO", name: "HONDURAS" },
  { code: "HK", name: "HONG KONG" },
  { code: "HU", name: "HUNGARY" },
  { code: "IC", name: "ICELAND" },
  { code: "IU", name: "IN ABSENTIA/UNKNOWN" },
  { code: "IN", name: "INDIA" },
  { code: "ID", name: "INDONESIA" },
  { code: "IR", name: "IRAN" },
  { code: "IZ", name: "IRAQ" },
  { code: "EI", name: "IRELAND" },
  { code: "IS", name: "ISRAEL" },
  { code: "IT", name: "ITALY" },
  { code: "IV", name: "IVORY COAST (COTE D'IVOIRE)" },
  { code: "JM", name: "JAMAICA" },
  { code: "JA", name: "JAPAN" },
  { code: "JO", name: "JORDAN" },
  { code: "CB", name: "KAMPUCHEA" },
  { code: "KZ", name: "KAZAKHSTAN" },
  { code: "KE", name: "KENYA" },
  { code: "KG", name: "KIRGHIZIA (KYRGYZSTAN)" },
  { code: "KR", name: "KIRIBATI" },
  { code: "KV", name: "KOSOVO" },
  { code: "KU", name: "KUWAIT" },
  { code: "LA", name: "LAOS" },
  { code: "LV", name: "LATVIA" },
  { code: "LE", name: "LEBANON" },
  { code: "LT", name: "LESOTHO" },
  { code: "LI", name: "LIBERIA" },
  { code: "LY", name: "LIBYA" },
  { code: "LS", name: "LIECHTENSTEIN" },
  { code: "LH", name: "LITHUANIA" },
  { code: "LU", name: "LUXEMBOURG" },
  { code: "MC", name: "MACAU" },
  { code: "MM", name: "MACEDONIA" },
  { code: "MA", name: "MADAGASCAR" },
  { code: "MI", name: "MALAWI" },
  { code: "MY", name: "MALAYSIA" },
  { code: "MV", name: "MALDIVES" },
  { code: "ML", name: "MALI" },
  { code: "MT", name: "MALTA" },
  { code: "MB", name: "MARTINIQUE" },
  { code: "MR", name: "MAURITANIA" },
  { code: "MP", name: "MAURITIUS" },
  { code: "MX", name: "MEXICO" },
  { code: "MQ", name: "MIDWAY ISLANDS" },
  { code: "MD", name: "MOLDAVIA (MOLDOVA)" },
  { code: "MN", name: "MONACO" },
  { code: "MG", name: "MONGOLIA" },
  { code: "MJ", name: "MONTENEGRO" },
  { code: "MH", name: "MONTSERRAT" },
  { code: "MO", name: "MOROCCO" },
  { code: "MZ", name: "MOZAMBIQUE" },
  { code: "WA", name: "NAMIBIA" },
  { code: "NR", name: "NAURU" },
  { code: "NP", name: "NEPAL" },
  { code: "NL", name: "NETHERLANDS" },
  { code: "NA", name: "NETHERLANDS ANTILLES" },
  { code: "NC", name: "NEW CALEDONIA" },
  { code: "NZ", name: "NEW ZEALAND" },
  { code: "NU", name: "NICARAGUA" },
  { code: "NG", name: "NIGER" },
  { code: "NI", name: "NIGERIA" },
  { code: "NE", name: "NIUE" },
  { code: "NN", name: "NO NATIONALITY" },
  { code: "NF", name: "NORFOLK ISLAND" },
  { code: "KN", name: "NORTH KOREA" },
  { code: "NO", name: "NORWAY" },
  { code: "MU", name: "OMAN" },
  { code: "PK", name: "PAKISTAN" },
  { code: "PN", name: "PALESTINE" },
  { code: "PM", name: "PANAMA" },
  { code: "PP", name: "PAPUA NEW GUINEA" },
  { code: "PA", name: "PARAGUAY" },
  { code: "DM", name: "PEOPLE'S REPUBLIC OF BENIN" },
  { code: "PE", name: "PERU" },
  { code: "RP", name: "PHILIPPINES" },
  { code: "PC", name: "PITCAIRN ISLANDS" },
  { code: "PL", name: "POLAND" },
  { code: "PO", name: "PORTUGAL" },
  { code: "QA", name: "QATAR" },
  { code: "RE", name: "REUNIOUN" },
  { code: "RO", name: "ROMANIA" },
  { code: "RU", name: "RUSSIA" },
  { code: "RW", name: "RWANDA" },
  { code: "WS", name: "SAMOA" },
  { code: "SM", name: "SAN MARINO" },
  { code: "TP", name: "SAO TOME AND PRINCIPE" },
  { code: "SA", name: "SAUDI ARABIA" },
  { code: "SG", name: "SENEGAL" },
  { code: "RS", name: "SERBIA" },
  { code: "SE", name: "SEYCHELLES" },
  { code: "SL", name: "SIERRA LEONE" },
  { code: "SN", name: "SINGAPORE" },
  { code: "SR", name: "SLOVAK REPUBLIC" },
  { code: "SV", name: "SLOVENIA" },
  { code: "BP", name: "SOLOMON ISLANDS" },
  { code: "SO", name: "SOMALIA" },
  { code: "SF", name: "SOUTH AFRICA" },
  { code: "KS", name: "SOUTH KOREA" },
  { code: "XS", name: "SOUTH SUDAN" },
  { code: "SP", name: "SPAIN" },
  { code: "CE", name: "SRI LANKA" },
  { code: "SC", name: "ST. CHRISTOPHER-NEVIS" },
  { code: "SH", name: "ST. HELENA" },
  { code: "SK", name: "ST. KITTS, WEST INDIES" },
  { code: "ST", name: "ST. LUCIA" },
  { code: "SB", name: "ST. PIERRE AND MIQUELON" },
  { code: "VC", name: "ST. VINCENT AND THE GRENADINES" },
  { code: "SS", name: "STATELESS - ALIEN UNABLE TO NAME A COUNTRY" },
  { code: "SU", name: "SUDAN" },
  { code: "NS", name: "SURINAME" },
  { code: "WZ", name: "SWAZILAND" },
  { code: "SW", name: "SWEDEN" },
  { code: "SZ", name: "SWITZERLAND" },
  { code: "SY", name: "SYRIA" },
  { code: "TW", name: "TAIWAN" },
  { code: "TA", name: "TAJIKISTAN (TADZHIK)" },
  { code: "TZ", name: "TANZANIA" },
  { code: "TH", name: "THAILAND" },
  { code: "PS", name: "THE REPUBLIC OF PALAU" },
  { code: "RM", name: "THE REPUBLIC OF THE MARSHALL ISLANDS" },
  { code: "TO", name: "TOGO" },
  { code: "TL", name: "TOKELAU" },
  { code: "TN", name: "TONGA" },
  { code: "TD", name: "TRINIDAD AND TOBAGO" },
  { code: "TS", name: "TUNISIA" },
  { code: "TU", name: "TURKIYE" },
  { code: "TR", name: "TURKMENISTAN" },
  { code: "TK", name: "TURKS AND CAICOS ISLANDS" },
  { code: "TV", name: "TUVALU" },
  { code: "UG", name: "UGANDA" },
  { code: "UE", name: "UKRAINE" },
  { code: "TC", name: "UNITED ARAB EMIRATES" },
  { code: "UK", name: "UNITED KINGDOM" },
  { code: "UN", name: "UNKNOWN NATIONALITY" },
  { code: "UV", name: "UPPER VOLTA" },
  { code: "UY", name: "URUGUAY" },
  { code: "UZ", name: "UZBEKISTAN" },
  { code: "NH", name: "VANUATU" },
  { code: "VE", name: "VENEZUELA" },
  { code: "VM", name: "VIETNAM" },
  { code: "WI", name: "WESTERN SAHARA" },
  { code: "YE", name: "YEMEN" },
  { code: "CG", name: "ZAIRE" },
  { code: "ZA", name: "ZAMBIA" },
  { code: "ZI", name: "ZIMBABWE" },
];

/** Exactly how ACIS labels an option in its nationality dropdown. */
export function eoirNationalityLabel(n: EoirNationality): string {
  return `${n.name} (${n.code})`;
}

export function findEoirNationality(code: string): EoirNationality | null {
  return EOIR_NATIONALITIES.find((n) => n.code === code) ?? null;
}
